# Exported from Render on 2026-10-01T08:02:23Z
version: "1"
services:
- type: web
  name: University-Student-Chatbot
  runtime: node
  repo: https://github.com/shikhachaudhary6869-tech/University-Student-Chatbot
  plan: free
  envVars:
  - key: GEMINI_API_KEY
    sync: false
  region: oregon
  buildCommand: yarn
  startCommand: node index.js
  autoDeployTrigger: commit
